language: java
jdk:
  -oraclejdk11
script : ant build
deploy:
  - provider: s3
    access_key_id: $aws_acc_key
    secret_access_key: $aws_access
    bucket: 'soumya-bucket-aws'
    region: 'us-east-2'
    skip_cleanup: true
  
  
