language: java
jdk:
  -oraclejdk11
script: ant build

deploy:
  - provider: s3
    access_key_id: $aws_access
    secret_access_key : $aws_acc_key
    bucket: 'soumya123'
    skip_cleanup: true
  
  
