language: java
jdk:
  -oraclejdk11
script : ant build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS
    secret_access_key: $AWS_KEY
    bucket: 'soumya-bucket-aws'
    region: 'us-east-2'
    skip_cleanup: true
  
  
